
quarkus:
   datasource:
      db-kind: oracle 
      jdbc:
        driver: oracle.jdbc.OracleDriver
        url:  jdbc:oracle:thin:@1.2.1.1:1245NaN/test
      username: test
      password: ss010
# drop and create the database at startup (use `update` to only update the schema)
   hibernate-orm:
      database:
         generation: update
